name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows, freebsd, openbsd]
        goarch: [amd64, arm64, arm, '386']
        exclude:
          - goos: darwin
            goarch: '386'
          - goos: darwin
            goarch: arm
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        export GOOS=${{ matrix.goos }}
        export GOARCH=${{ matrix.goarch }}
        export CGO_ENABLED=0
        go build -v -trimpath -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o wantastic-wgclient-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/wantastic-wgclient

    - name: Package
      run: |
        export GOOS=${{ matrix.goos }}
        export GOARCH=${{ matrix.goarch }}
        BINARY_NAME="wantastic-wgclient-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          mv "${BINARY_NAME}" wantastic-wgclient.exe
          zip "wantastic-wgclient-${GOOS}-${GOARCH}.zip" wantastic-wgclient.exe README.md
        else
          tar -czvf "wantastic-wgclient-${GOOS}-${GOARCH}.tar.gz" "${BINARY_NAME}" README.md
        fi

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wantastic-wgclient-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        asset_name: wantastic-wgclient-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Asset (Windows)
      if: matrix.goos == 'windows'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wantastic-wgclient-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_name: wantastic-wgclient-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        asset_content_type: application/zip
