name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [386, amd64, arm, arm64, loong64, mips, mips64, mips64le, mipsle, ppc64, ppc64le, riscv64, s390x] 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: Build
      run: |
        export GOOS=${{ matrix.goos }}
        export GOARCH=${{ matrix.goarch }}
        export CGO_ENABLED=0
        go build -v -trimpath -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o wantasticd-${{ matrix.goarch }} ./cmd/wantasticd

    - name: Package
      run: |
        export GOARCH=${{ matrix.goarch }}
        BINARY_NAME="wantasticd-${GOARCH}"
        cp install.sh "${BINARY_NAME}-install.sh"
        chmod +x "${BINARY_NAME}-install.sh"
        tar -czvf "wantasticd-${GOARCH}.tar.gz" "${BINARY_NAME}" README.md "${BINARY_NAME}-install.sh"

    - name: Upload Release Asset
      run: |
        gh release upload ${{ github.ref_name }} wantasticd-${{ matrix.goarch }}.tar.gz --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
